#Type of containers that can be linked together
#WARNING: Only add container blocks here - If you add any other type of block there might be malfunctions!
#Deafults: Chest, Barrel, Trapped_Chest
containers:
  - Chest
  - Barrel
  - Trapped_Chest

#The item used to link containers
#Default: Stick
linking-item: Stick

#Delay between item transferring in ticks (20 ticks = 1 second)
#WARNING: If you have a lot of linked containers on your server, setting this to a low number might decrease its performance
#Note that the default value of 8 is the same as minecraft's hopper delay time (unless you changed it in spigot.yml)
#Default: 8
transfer-delay: 8

#Whether particles should be displayed from containers transferring items
#Default: true
enable-particles: true

#Wheter players need the permission storageLinking.use to link containers
#Default: false
enable-usage-permission: false

#Whether a no permission message should be displayed to players when attempting to link containers without having the storageLinking.use permission
#Only applied when "enable-usage-permission" is true
#Default: true
no-usage-permission-message: true
