#Type of containers that can be linked together
#WARNING: Only add container blocks here - If you add any other type of block there might be malfunctions!
containers:
  - Chest
  - Barrel
  - Trapped_Chest

#The item used to link containers
linkingItem: Stick

#Delay between item transferring in ticks (20 ticks = 1 second)
#WARNING: If you have a lot of linked containers on your server, setting this to a low number might decrease your server performance
#Note that the default value of 8 is the same as minecraft's hopper delay time (unless you changed it in spigot.yml)
#Changes only apply after restart
transfer-delay: 8

#Whether particles should be enabled and displayed or not
enable-particles: true