name: StorageLinking
version: '${project.version}'
main: raffel080108.storagelinking.Main
api-version: 1.18

commands:
    storageLinking:
        description: StorageLinking commands - Use with no arguments for list of commands
        usage: /storageLinking